export const CREATE_STORY_REQUEST = "CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAILURE = "CREATE_STORY_FAILURE";

export const VIEW_STORY_REQUEST = "VIEW_STORY_REQUEST";
export const VIEW_STORY_SUCCESS = "VIEW_STORY_SUCCESS";
export const VIEW_STORY_FAILURE = "VIEW_STORY_FAILURE";

export const GET_FOLLOWED_USER_STORIES_REQUEST = "GET_FOLLOWED_USER_STORIES_REQUEST";
export const GET_FOLLOWED_USER_STORIES_SUCCESS = "GET_FOLLOWED_USER_STORIES_SUCCESS";
export const GET_FOLLOWED_USER_STORIES_FAILURE = "GET_FOLLOWED_USER_STORIES_FAILURE";

export const GET_VIEWERS_REQUEST = "GET_VIEWERS_REQUEST";
export const GET_VIEWERS_SUCCESS = "GET_VIEWERS_SUCCESS";
export const GET_VIEWERS_FAILURE = "GET_VIEWERS_FAILURE";

export const DELETE_STORY_REQUEST = "DELETE_STORY_REQUEST";
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";
export const DELETE_STORY_FAILURE = "DELETE_STORY_FAILURE";

export const LIKE_STORY_REQUEST = 'LIKE_STORY_REQUEST';
export const LIKE_STORY_SUCCESS = 'LIKE_STORY_SUCCESS';
export const LIKE_STORY_FAILURE = 'LIKE_STORY_FAILURE';

export const GET_LIKERS_REQUEST = 'GET_LIKERS_REQUEST';
export const GET_LIKERS_SUCCESS = 'GET_LIKERS_SUCCESS';
export const GET_LIKERS_FAILURE = 'GET_LIKERS_FAILURE';