export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE"

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE"

export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST"
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS"
export const GET_USER_POSTS_FAILURE = "GET_USER_POSTS_FAILURE"

export const GET_USER_LIKE_POSTS_REQUEST = "GET_USER_LIKE_POSTS_REQUEST"
export const GET_USER_LIKE_POSTS_SUCCESS = "GET_USER_LIKE_POSTS_SUCCESS"
export const GET_USER_LIKE_POSTS_FAILURE = "GET_USER_LIKE_POSTS_FAILURE"

export const GET_USER_SAVED_POSTS_REQUEST = "GET_USER_SAVED_POSTS_REQUEST"
export const GET_USER_SAVED_POSTS_SUCCESS = "GET_USER_SAVED_POSTS_SUCCESS"
export const GET_USER_SAVED_POSTS_FAILURE = "GET_USER_SAVED_POSTS_FAILURE"

export const GET_FOLLOWING_USER_POSTS_REQUEST = "GET_FOLLOWING_USER_POSTS_REQUEST"
export const GET_FOLLOWING_USER_POSTS_SUCCESS = "GET_FOLLOWING_USER_POSTS_SUCCESS"
export const GET_FOLLOWING_USER_POSTS_FAILURE = "GET_FOLLOWING_USER_POSTS_FAILURE"

export const GET_TRENDING_POSTS_REQUEST = "GET_TRENDING_POSTS_REQUEST"
export const GET_TRENDING_POSTS_SUCCESS = "GET_TRENDING_POSTS_SUCCESS"
export const GET_TRENDING_POSTS_FAILURE = "GET_TRENDING_POSTS_FAILURE"

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"

export const SAVE_POST_REQUEST = "SAVE_POST_REQUEST"
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS"
export const SAVE_POST_FAILURE = "SAVE_POST_FAILURE"

export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS"
export const SHARE_POST_FAILURE = "SHARE_POST_FAILURE"
export const SHARE_POST_REQUEST = "SHARE_POST_REQUEST"

export const FIND_POST_BY_ID_REQUEST = "FIND_POST_BY_ID_REQUEST"
export const FIND_POST_BY_ID_SUCCESS = "FIND_POST_BY_ID_SUCCESS"
export const FIND_POST_BY_ID_FAILURE = "FIND_POST_BY_ID_FAILURE"

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST"
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS"
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE"
