export const SEND_NOTIFICATION_REQUEST = "SEND_NOTIFICATION_REQUEST";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAILURE = "SEND_NOTIFICATION_FAILURE";

export const GET_USER_NOTIFICATIONS_REQUEST = "GET_USER_NOTIFICATIONS_REQUEST";
export const GET_USER_NOTIFICATIONS_SUCCESS = "GET_USER_NOTIFICATIONS_SUCCESS";
export const GET_USER_NOTIFICATIONS_FAILURE = "GET_USER_NOTIFICATIONS_FAILURE";

export const GET_USER_UNREAD_NOTIFICATIONS_REQUEST = "GET_USER_UNREAD_NOTIFICATIONS_REQUEST";
export const GET_USER_UNREAD_NOTIFICATIONS_SUCCESS = "GET_USER_UNREAD_NOTIFICATIONS_SUCCESS";
export const GET_USER_UNREAD_NOTIFICATIONS_FAILURE = "GET_USER_UNREAD_NOTIFICATIONS_FAILURE";

export const MARK_NOTIFICATION_AS_READ_REQUEST = "MARK_NOTIFICATION_AS_READ_REQUEST";
export const MARK_NOTIFICATION_AS_READ_SUCCESS = "MARK_NOTIFICATION_AS_READ_SUCCESS";
export const MARK_NOTIFICATION_AS_READ_FAILURE = "MARK_NOTIFICATION_AS_READ_FAILURE";

export const MARK_ALL_NOTIFICATIONS_AS_READ_REQUEST = "MARK_ALL_NOTIFICATIONS_AS_READ_REQUEST";
export const MARK_ALL_NOTIFICATIONS_AS_READ_SUCCESS = "MARK_ALL_NOTIFICATIONS_AS_READ_SUCCESS";
export const MARK_ALL_NOTIFICATIONS_AS_READ_FAILURE = "MARK_ALL_NOTIFICATIONS_AS_READ_FAILURE";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";