export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST";
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const FIND_USER_BY_ID_FAILURE = "FIND_USER_BY_ID_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";

export const SUGGEST_USER_REQUEST = "SUGGEST_USER_REQUEST";
export const SUGGEST_USER_SUCCESS = "SUGGEST_USER_SUCCESS";
export const SUGGEST_USER_FAILURE = "SUGGEST_USER_FAILURE";

export const GET_USER_FOLLOWERS_REQUEST = "GET_USER_FOLLOWERS_REQUEST";
export const GET_USER_FOLLOWERS_SUCCESS = "GET_USER_FOLLOWERS_SUCCESS";
export const GET_USER_FOLLOWERS_FAILURE = "GET_USER_FOLLOWERS_FAILURE";

export const GET_USER_FOLLOWINGS_REQUEST = "GET_USER_FOLLOWINGS_REQUEST";
export const GET_USER_FOLLOWINGS_SUCCESS = "GET_USER_FOLLOWINGS_SUCCESS";
export const GET_USER_FOLLOWINGS_FAILURE = "GET_USER_FOLLOWINGS_FAILURE";

export const UPGRADE_TO_PREMIUM_REQUEST = "UPGRADE_TO_PREMIUM_REQUEST";
export const UPGRADE_TO_PREMIUM_SUCCESS = "UPGRADE_TO_PREMIUM_SUCCESS";
export const UPGRADE_TO_PREMIUM_FAILURE = "UPGRADE_TO_PREMIUM_FAILURE";

export const CLEAR_USER = "CLEAR_USER"
